# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtrack',
            name='image',
            field=models.ImageField(blank=True, upload_to='get_music_image_path'),
        ),
    ]
