# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20160531_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtrack',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
