# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0007_artwork_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='literature', to='general.ArtWork')),
            ],
        ),
    ]
