# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0006_auto_20160531_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='get_picture_image_path')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='general.ArtWork')),
            ],
        ),
    ]
