# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='accounts/avatar/', verbose_name='avatar')),
            ],
        ),
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.ArtUser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0)),
                ('art_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.ArtWork')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.ArtUser')),
            ],
        ),
        migrations.AddField(
            model_name='artuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='general.ArtWork'),
        ),
        migrations.AddField(
            model_name='artuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='general.ArtUser'),
        ),
        migrations.AddField(
            model_name='artuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
