# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20160531_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
