# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20160531_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
