# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20160531_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
