# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_artwork_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='art_work',
            new_name='artwork',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
